### ISSUE TITLE
typo in requirements.txt

### ISSUE THREAD

**Issue by Hiromasa-H** [MaybeShewill-CV/segment-anything-u-specify#1]
There is a minor typo in the [requirements.txt file on line2](https://github.com/MaybeShewill-CV/segment-anything-u-specify/blob/main/requirements.txt#L2) where there is an unnecessary '=' sign after `logru`:

```
ftfy
loguru=
matplotlib
```

The below pull request should get rid of it.

**Comment by MaybeShewill-CV** [comment]
@Hiromasa-H PR merged:)
