### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Xuefei98** [MaybeShewill-CV/segment-anything-u-specify#11]
First of all, great work and thank you for open source all of the code! I was trying to test the model with bear example. But it returns the RuntimeError as "RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 3.94 GiB total capacity; 2.92 GiB already allocated; 364.19 MiB free; 2.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF". I wonder what kind of GPU are you using? It doesn't make sense that the segmentation for one image needs that much CUDA memory though. Thanks!

**Comment by MaybeShewill-CV** [comment]
@Xuefei98 GTX 1070 and RTX 3080 works fine:)

**Comment by Xuefei98** [comment]
Unfortunately I only have a GTX 1050 on my thinkpad :( Is there any possible solution you would recommend except getting new GPUs?

**Comment by Xuefei98** [comment]
The model will run if I use MobileSam. Thanks!
