### ISSUE TITLE
It fails in nature envs

### ISSUE THREAD

**Issue by cuge1995** [MaybeShewill-CV/segment-anything-u-specify#3]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/48620704/234783327-a7463b30-364a-4783-bc24-830f10868f02.png">

**Comment by cuge1995** [comment]
ori image is like
<img width="473" alt="image" src="https://user-images.githubusercontent.com/48620704/234783633-60d27907-bea1-4ec0-8b91-9259a4ff8661.png">

**Comment by MaybeShewill-CV** [comment]
@cuge1995 Maybe the strawberry is too small to segment. Here is the result after exec python tools/sam_clip_text_seg.py --input_image_path ~/Desktop/test_env.png --text "leaf,strawberry" --cls_score_thresh 0.9 --use_text_prefix --save_dir ~/Desktop/

**Comment by MaybeShewill-CV** [comment]
![result](https://user-images.githubusercontent.com/15725187/234826160-c65a1ec1-1e54-4b7d-a9d0-edabaf92c391.png)
