### ISSUE TITLE
inference on geotiff and output as geojson

### ISSUE THREAD

**Issue by mohammadreza-sheykhmousa** [MaybeShewill-CV/segment-anything-u-specify#4]
Dear team,

Firstly, I would like to extend my gratitude for the incredible work that you have done on this project. It is truly fascinating and I appreciate the effort you have put into it.

I have a query regarding running the inference on a multispectral satellite image with more than 3 channels or bands. I have attempted to do so with a 4 bands image, however, it did not work. Can you suggest any workaround for this issue?

Furthermore, for geospatial data related to satellite imagery, I would also like to request a geojson of the polygonized mask, in addition to the mask, if possible.

Thank you again for your fantastic work and I look forward to your response.

Best regards,

**Comment by MaybeShewill-CV** [comment]
@mohammadreza-sheykhmousa 1. multispectral satellite image should be transformed to rgb image or 3-channel image before inference.
2.As for geojson you could search for other python package to help you transform the segmentation mask into it:)
