### ISSUE TITLE
ModuleNotFoundError: No module named 'local_utils'

### ISSUE THREAD

**Issue by ghost** [MaybeShewill-CV/segment-anything-u-specify#7]
作者你好，按照你的步驟安裝
執行python tools/sam_clip_text_seg.py --input_image_path ./data/test_images/test_bear.jpg --text bear
顯示Traceback (most recent call last):
  File "tools/sam_clip_text_seg.py", line 17, in <module>
    from local_utils.log_util import init_logger
ModuleNotFoundError: No module named 'local_utils'

不清楚哪邊出了問題

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 测试前 前进入项目根目录执行 export PYTHONPATH=$PWD:$PYTHONPATH

**Comment by ghost** [comment]
@MaybeShewill-CV 
![image](https://github.com/MaybeShewill-CV/segment-anything-u-specify/assets/110151053/6352694a-2bfa-4ec5-b8c4-88206e493ec7)
 明明有安裝cuda，不曉得為何會跳錯誤，最下面是cuda版本
 windows10 系統

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 应该不是你cuda安装的问题 是你gpu版本的pytorch安装错误。建议查看官方文档 https://pytorch.org/get-started/locally/

**Comment by ghost** [comment]
OK了，重裝pytorch就可以運行了
但有一個小問題是，為何output的圖片，會resize1280大小?
我input是一張1920*1080

另外好奇問一下，未來是否有支援export的json等info，bbox大小 segment point，count數量等
謝謝

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 https://github.com/MaybeShewill-CV/segment-anything-u-specify/blob/main/config/insseg.yaml 这里限制了最大的图像大小，你可以自己更改配置。 export的json等这个你可以自己后处理mask得到相关的信息，这个需求目前看不是非常通用，暂时不会添加相关功能。

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 欢迎star项目 :)

**Comment by ghost** [comment]
@MaybeShewill-CV 本來就已經給星星了
另外，想建議你在github補充說明一下，如果是windows系統，應該不是用export PYTHONPATH=$PWD:$PYTHONPATH
而是set PYTHONPATH=%PYTHONPATH%;C:\Users\User\Desktop\segment-anything-u-specify
;後面+路徑

另外想了解一下--use_text_prefix是甚麼，還是有點不清楚用法
這張是有使用--use_text_prefix指令
![43_insseg_add](https://github.com/MaybeShewill-CV/segment-anything-u-specify/assets/110151053/ca04bda4-f5a9-4ce2-9cc9-bd61aa00cff0)
這張沒有指令
![43_insseg_add](https://github.com/MaybeShewill-CV/segment-anything-u-specify/assets/110151053/f2cb056e-f8bd-426e-aa02-654c8ad7b69f)

**Comment by ghost** [comment]
執行python tools/cluster_sam.py --input_image_path ./data/test_images/test_bear.jpg --simi_thresh 0.82
會發生錯誤，解決方式如下面文章
https://blog.csdn.net/qq_45266796/article/details/109028605

import os
os.environ["KMP_DUPLICATE_LIB_OK"]  =  "TRUE"
新增此代碼進去，就不會發生錯誤了


另外同樣上面那串指令，為何得出來的圖跟你長得不一樣
![test_bear_ori_mask](https://github.com/MaybeShewill-CV/segment-anything-u-specify/assets/110151053/ff168a85-3f69-4f5d-9096-ed9b214956a5)
多了很多BBOX跟無相關的labels

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 如果使用了 "use_text_prefix" 会给你输入的标签加一个固定的开头 “a photo of xxx”

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 windows平台确实没有测试过，因为目前我这边没有这个平台，下来有机会我会在windows上测试下看看：）

**Comment by ghost** [comment]
@MaybeShewill-CV --use_text_prefix 加了這個指令，並沒有多了a photo of 此前綴....
而且就如同上面我給的那兩張圖，明明下的指令只多一個--use_text_prefix，為何結果會不一樣?
加了--use_text_prefix顯示4台，沒加--use_text_prefix 反而顯示6台車

另外mask圖，很多label都重疊再一起，是不是就無解了?(如同上面那張mask圖)

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 代码内部会给text label加前缀，可以参考 https://github.com/MaybeShewill-CV/segment-anything-u-specify/blob/3aa484744f6d23117727cdae79b88c76c6b96c1a/models/detector/utils.py#L104-L118

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 做检测请使用tools/sam_clip_text_seg.py

**Comment by ghost** [comment]
https://github.com/MaybeShewill-CV/segment-anything-u-specify/assets/110151053/5d15fcbf-3a42-49db-ad3d-ec3e9baeb7c9

我錄製video，代碼都沒更動過，輸出的結果，檔名並沒有a photo of 相關字眼
另外 也是沒解決我的疑問，就是多了--use_text_prefix command ，為何顯示車子數量不同?
我明白做檢測要用sam_clip_text_seg，只是偶爾也要處理全景分割，因此會用到cluster_sam.py

只是好奇為何代碼都一樣，只差在系統不同，為何你的bear圖跟我的圖 是不一樣

謝謝你的耐心回應

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 多了 --use_text_prefix 之后text会从 “xx” 变成 “a photo of xx”，那么相应的text embedding也会变动，clip的结果就会不同。
cluster_sam.py 可能无法很好支持全景分割 :)

**Comment by ghost** [comment]
就我的理解，是不是 --use_text_prefix是大分類的意思? 如果沒有 --use_text_prefix，出來結果就是小分類?
例如car車子 是大分類， car的小分類可能還有truck, van等，不知道是否理解正確?

有關全景分割部分，不知道有無優化可能?
例如https://github.com/fudan-zvg/Semantic-Segment-Anything 
他的代碼我執行不了，但有測試他的demo，效果還行

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 --use_text_prefix并不是你理解的意思，它就是我之前给你解释的意思，只是给你提供的label增加了一个固定的text prefix。
https://github.com/fudan-zvg/Semantic-Segment-Anything 你可以尝试一下：）

**Comment by ghost** [comment]
SSA 我本地端環境一直建置不了 才想問你的model能否加入SSA測試優化

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 SSA的问题你可以求助一下他们的contributor哈：）

**Comment by ghost** [comment]
其實我的原意是 你採用SSA的方式來完成全景分割 SSA的全景分割效果較好於現在版本 哈哈

**Comment by MaybeShewill-CV** [comment]
@stphtan94117 Thanks :)
